# Site settings
title: "Battlefield 6 Weapon Statistics"
description: "Interactive web dashboard analyzing 31 weapons across 4 classes with comprehensive performance metrics"
url: "https://bdeland.github.io"
baseurl: "/bf6_guns"

# Theme
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Author
author:
  name: "bdeland"
  url: "https://github.com/bdeland"

# GitHub
github:
  repository_url: "https://github.com/bdeland/bf6_guns"
  is_project_page: true

# Navigation
show_downloads: true

# Exclude from processing
exclude:
  - requirements.txt
  - analyze_weapons.py
  - data.csv
  - analysis_output/
  - .gitignore
  - LICENSE

# Include files
include:
  - data.js
  - app.js
  - styles.css

